# Generated by Django 4.0 on 2021-12-20 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date_create_contract')),
                ('id_contract', models.CharField(max_length=20, unique=True, verbose_name='id_contract')),
            ],
        ),
        migrations.CreateModel(
            name='CreditApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date_create_application')),
                ('id_application', models.CharField(max_length=20, unique=True, verbose_name='id_application')),
                ('id_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getidapp.contracts')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date_create_product')),
                ('name_product', models.CharField(max_length=50, unique=True, verbose_name='Name_product')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getidapp.creditapplications')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date_create_manufacturer')),
                ('id_manufacturer', models.CharField(max_length=20, verbose_name='Id_manufacturer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getidapp.products')),
            ],
        ),
    ]
